- name: /random_filter
  publish: [/filtered_points, /points_downsampler_info]
  subscribe: [/config/random_filter, /points_raw]
- name: /voxel_grid_filter
  publish: [/filtered_points, /points_downsampler_info]
  subscribe: [/config/voxel_grid_filter, /points_raw]
